In [1]:
import numpy as np

In [2]:
print(np.arange(7))
print(np.arange(1,7))
print(np.arange(1,7,2))

[0 1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 3 5]


In [4]:
x = np.arange(3)
y = np.arange(5)
X, Y = np.meshgrid(x, y)
print(X)
print(Y)

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [5]:
x = np.arange(12)
rx = x.reshape(3,4)
print(rx)
print(rx.ravel())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 6, 5])
np.c_[a, b]

array([[1, 4],
       [2, 6],
       [3, 5]])