In [1]:
import pandas as pd


text = [
    '남북 고위급회담 대표단 확정..남북 해빙모드 급물살',
    '[남북 고위급 회담]장차관만 6명..판 커지는 올림픽 회담',
    
    '문재인 대통령과 대통령의 영부인 김정숙여사 내외의 동반 1987 관람 후 인터뷰',
    '1987 본 문 대통령.."그런다고 바뀌나? 함께 하면 바뀐다"',
    
    '이명박 전 대통령과 전 대통령의 부인 김윤옥 여사, 그리고 전 대통령의 아들 이시형씨의 동반 검찰출석이 기대됨'
]
 

In [2]:
from konlpy.tag import Okt
tagger = Okt()

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
#CountVectorizer는 토큰의 문서별 등장 횟수를 행렬로 정리해서 보여줌.
cv = CountVectorizer(tokenizer=tagger.nouns)

In [4]:
tdm = cv.fit_transform(text)
#fit_transform은 fit과 transform두개의 메소드를 합친것.
test1 = cv.fit(text)
print(test1)
test2 = cv.transform(text)
print(test2)


CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=<bound method Okt.nouns of <konlpy.tag._okt.Okt object at 0x0000000004CF03C8>>,
        vocabulary=None)
  (0, 1)	1
  (0, 3)	1
  (0, 7)	2
  (0, 9)	1
  (0, 11)	1
  (0, 14)	1
  (0, 17)	1
  (0, 31)	1
  (0, 32)	1
  (0, 33)	1
  (1, 1)	1
  (1, 7)	1
  (1, 13)	1
  (1, 22)	1
  (1, 26)	1
  (1, 28)	1
  (1, 30)	1
  (1, 33)	2
  (2, 2)	1
  (2, 6)	1
  (2, 8)	1
  (2, 10)	2
  (2, 12)	1
  (2, 16)	1
  (2, 20)	1
  (2, 21)	1
  (2, 25)	1
  (2, 34)	1
  (3, 10)	1
  (3, 15)	1
  (4, 0)	1
  (4, 4)	1
  (4, 5)	1
  (4, 10)	3
  (4, 12)	1
  (4, 18)	1
  (4, 19)	1
  (4, 20)	1
  (4, 23)	1
  (4, 24)	1
  (4, 27)	3
  (4, 29)	1


In [5]:
print(tdm)

  (0, 17)	1
  (0, 3)	1
  (0, 14)	1
  (0, 31)	1
  (0, 32)	1
  (0, 9)	1
  (0, 11)	1
  (0, 33)	1
  (0, 1)	1
  (0, 7)	2
  (1, 22)	1
  (1, 30)	1
  (1, 13)	1
  (1, 28)	1
  (1, 26)	1
  (1, 33)	2
  (1, 1)	1
  (1, 7)	1
  (2, 25)	1
  (2, 34)	1
  (2, 2)	1
  (2, 12)	1
  (2, 8)	1
  (2, 20)	1
  (2, 6)	1
  (2, 21)	1
  (2, 10)	2
  (2, 16)	1
  (3, 15)	1
  (3, 10)	1
  (4, 4)	1
  (4, 29)	1
  (4, 0)	1
  (4, 24)	1
  (4, 19)	1
  (4, 5)	1
  (4, 18)	1
  (4, 27)	3
  (4, 23)	1
  (4, 12)	1
  (4, 20)	1
  (4, 10)	3


In [6]:
tdm.toarray() #각각의 리스트는 문자열 한 줄씩을 의미.

array([[0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 2, 0],
       [0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 2, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 3, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
        0, 1, 1, 0, 0, 3, 0, 1, 0, 0, 0, 0, 0]], dtype=int64)

In [7]:
tdm.sum(axis=0)

matrix([[1, 2, 1, 1, 1, 1, 1, 3, 1, 1, 6, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2,
         1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 3, 1]], dtype=int64)

In [10]:
# word_count = pd.DataFrame(
#     {'단어' : cv.get_feature_names(),
#      '빈도' : tdm.sum(axis=0).flat
#     }

# )


C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\dtypes.py:271: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if string == 'category':


In [11]:

word_count.sort_values('빈도', ascending=False)

단어  빈도
10  대통령   6
27    전   3
33   회담   3
7    남북   3
12   동반   2
1    고위   2
20   여사   2
22  올림픽   1
23  이명박   1
24  이시형   1
25  인터뷰   1
0    검찰   1
26    장   1
28   차관   1
29   출석   1
30    판   1
31   해빙   1
32   확정   1
21  영부인   1
17   물살   1
19   아들   1
18   부인   1
16  문재인   1
15    문   1
14   모드   1
13    명   1
11   대표   1
9     단   1
8    내외   1
6   김정숙   1
5   김윤옥   1
4    기대   1
3     급   1
2    관람   1
34    후   1

In [13]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer()
tdm2 = tfidf.fit_transform(tdm)
words = cv.get_feature_names()
print(tdm2)
print(words)
for i, n in sorted(zip(tdm[0].indices, tdm[0].data)):
    print(words[i], n)
for i, n in sorted(zip(tdm2[0].indices, tdm2[0].data)):
    print(words[i], n)

  (0, 33)	0.24430917615542821
  (0, 32)	0.3028149266649128
  (0, 31)	0.3028149266649128
  (0, 17)	0.3028149266649128
  (0, 14)	0.3028149266649128
  (0, 11)	0.3028149266649128
  (0, 9)	0.3028149266649128
  (0, 7)	0.48861835231085643
  (0, 3)	0.3028149266649128
  (0, 1)	0.24430917615542821
  (1, 33)	0.5407087874491917
  (1, 30)	0.33509730251460906
  (1, 28)	0.33509730251460906
  (1, 26)	0.33509730251460906
  (1, 22)	0.33509730251460906
  (1, 13)	0.33509730251460906
  (1, 7)	0.27035439372459585
  (1, 1)	0.27035439372459585
  (2, 34)	0.3147224767563814
  (2, 25)	0.3147224767563814
  (2, 21)	0.3147224767563814
  (2, 20)	0.2539161125931929
  (2, 16)	0.3147224767563814
  (2, 12)	0.2539161125931929
  (2, 10)	0.42154662126676445
  (2, 8)	0.3147224767563814
  (2, 6)	0.3147224767563814
  (2, 2)	0.3147224767563814
  (3, 15)	0.830880748357988
  (3, 10)	0.5564505207186616
  (4, 29)	0.2115794233784669
  (4, 27)	0.6347382701354007
  (4, 24)	0.2115794233784669
  (4, 23)	0.2115794233784669
  (4, 20)	0.1

In [17]:
tdm[0].data

array([1, 1, 2, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [16]:
sorted(zip(tdm[0].indices, tdm[0].data))

[(1, 1),
 (3, 1),
 (7, 2),
 (9, 1),
 (11, 1),
 (14, 1),
 (17, 1),
 (31, 1),
 (32, 1),
 (33, 1)]

In [14]:
print(tdm[0].indices)
print(tdm[0].data)

[ 1  3  7  9 11 14 17 31 32 33]
[1 1 2 1 1 1 1 1 1 1]


In [15]:
words

['검찰',
 '고위',
 '관람',
 '급',
 '기대',
 '김윤옥',
 '김정숙',
 '남북',
 '내외',
 '단',
 '대통령',
 '대표',
 '동반',
 '명',
 '모드',
 '문',
 '문재인',
 '물살',
 '부인',
 '아들',
 '여사',
 '영부인',
 '올림픽',
 '이명박',
 '이시형',
 '인터뷰',
 '장',
 '전',
 '차관',
 '출석',
 '판',
 '해빙',
 '확정',
 '회담',
 '후']