In [1]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as py
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

df = pd.read_csv("regression.csv")
df

age  height  weight
0    1세    80.1    10.9
1    2세    87.8    13.2
2    3세    95.2    14.8
3    4세   102.3    16.7
4    5세   109.0    19.1
5    6세   115.5    21.5
6    7세   122.0    24.9
7    8세   127.8    28.5
8    9세   133.3    32.3
9   10세   138.0    35.4
10  11세   144.9    41.5
11  12세   150.7    45.2
12  13세   158.2    51.0
13  14세   164.7    57.1
14  15세   169.2    61.7
15  16세   170.3    63.4
16  17세   172.5    65.2
17  18세   172.9    67.4
18  19세   173.4    68.3

In [15]:
print(df.height)
print(df.height.values)
print(np.array(df.height.values).reshape(-1, 1))

0      80.1
1      87.8
2      95.2
3     102.3
4     109.0
5     115.5
6     122.0
7     127.8
8     133.3
9     138.0
10    144.9
11    150.7
12    158.2
13    164.7
14    169.2
15    170.3
16    172.5
17    172.9
18    173.4
Name: height, dtype: float64
[ 80.1  87.8  95.2 102.3 109.  115.5 122.  127.8 133.3 138.  144.9 150.7
 158.2 164.7 169.2 170.3 172.5 172.9 173.4]
[[ 80.1]
 [ 87.8]
 [ 95.2]
 [102.3]
 [109. ]
 [115.5]
 [122. ]
 [127.8]
 [133.3]
 [138. ]
 [144.9]
 [150.7]
 [158.2]
 [164.7]
 [169.2]
 [170.3]
 [172.5]
 [172.9]
 [173.4]]


In [2]:
lm = LinearRegression()
lm = lm.fit(np.array(df.height.values).reshape(-1, 1), np.array(df.weight.values).reshape(-1,1))
print(lm.coef_, lm.intercept_)

[[0.64199432]] [-48.59225733]


In [13]:
newH = [[170]]
newW = lm.predict(newH)
newW[0][0]

60.54677628008977

In [2]:
df = pd.read_csv("regression.csv")
df["age"] = df["age"].map(lambda x: int(x[:-1]))
df

age  height  weight
0     1    80.1    10.9
1     2    87.8    13.2
2     3    95.2    14.8
3     4   102.3    16.7
4     5   109.0    19.1
5     6   115.5    21.5
6     7   122.0    24.9
7     8   127.8    28.5
8     9   133.3    32.3
9    10   138.0    35.4
10   11   144.9    41.5
11   12   150.7    45.2
12   13   158.2    51.0
13   14   164.7    57.1
14   15   169.2    61.7
15   16   170.3    63.4
16   17   172.5    65.2
17   18   172.9    67.4
18   19   173.4    68.3

In [3]:
X = df[["height", "weight"]]
print(X)


    height  weight
0     80.1    10.9
1     87.8    13.2
2     95.2    14.8
3    102.3    16.7
4    109.0    19.1
5    115.5    21.5
6    122.0    24.9
7    127.8    28.5
8    133.3    32.3
9    138.0    35.4
10   144.9    41.5
11   150.7    45.2
12   158.2    51.0
13   164.7    57.1
14   169.2    61.7
15   170.3    63.4
16   172.5    65.2
17   172.9    67.4
18   173.4    68.3


In [4]:
Y = df[["age"]]
print(Y)

    age
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
10   11
11   12
12   13
13   14
14   15
15   16
16   17
17   18
18   19


In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, Y)
model = LinearRegression()


In [9]:
model.fit(X_train, y_train)
print(model.predict([[180, 80]]))

[[20.25746043]]


In [59]:
np.arange(10).reshape(-1, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [60]:
np.arange(10).reshape(-1, 1).reshape(1, -1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [61]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])