In [ ]:
import numpy as np
#
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import LeavePOut
from sklearn.model_selection import GroupKFold
from sklearn.model_selection import ShuffleSplit



# train_test_split

In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

x_data = np.array([
[2,1],
[3,2],
[3,4],
[5,5],
[7,5],
[2,5],
[9,2]
])
y_data = np.array([0,0,0,1,1,0,1]) 

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3)

logreg = LogisticRegression(solver='lbfgs', multi_class='auto')
# logreg = LogisticRegression()
clf =logreg.fit(x_train,y_train)
y_predict = clf.predict(x_test) 

score = accuracy_score(y_test, y_predict)
print(score)
y_predict


1.0


array([0, 0, 1])

# cross_val_score

In [56]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

x_data = np.array([
[2,1],
[3,2],
[3,4],
[5,5],
[7,5],
[2,5],
[9,2]
])
y_data = np.array([0,0,0,1,1,0,1]) 


logreg = LogisticRegression(solver='lbfgs', multi_class='auto')
#KFold: 3개 분할 => 3번 교차 

scores = cross_val_score(logreg, x_data, y_data)
print("교차 검증 점수:", scores)

교차 검증 점수: [0.66666667 1.         1.        ]


C:\Users\User\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


# KFold

In [57]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

x_data = np.array([
[2,1],
[3,2],
[3,4],
[5,5],
[7,5],
[2,5],
[9,2]
])
y_data = np.array([0,0,0,1,1,0,1]) 


logreg = LogisticRegression(solver='lbfgs', multi_class='auto')
#KFold: 3개 분할 => 3번 교차 
kf = KFold() 
print("교차 검증 점수:\n",cross_val_score(logreg, x_data, y_data, cv=kf))


교차 검증 점수:
 [1. 0. 1.]


C:\Users\User\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:426: FutureWarning: You should specify a value for 'n_splits' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(NSPLIT_WARNING, FutureWarning)


# StratifiedKFold

In [60]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

x_data = np.array([
[2,1],
[3,2],
[3,4],
[5,5],
[7,5],
[2,5],
[9,2]
])
y_data = np.array([0,0,0,1,1,0,1]) 

logreg = LogisticRegression(solver='lbfgs', multi_class='auto')
#3개 분할 => 3번 교차 
skf = StratifiedKFold(n_splits=3)

scores = cross_val_score(logreg, x_data, y_data, cv=skf)
print("교차 검증 점수:", scores)

교차 검증 점수: [0.66666667 1.         1.        ]


# KFold with shuffle

In [61]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

x_data = np.array([
[2,1],
[3,2],
[3,4],
[5,5],
[7,5],
[2,5],
[9,2]
])
y_data = np.array([0,0,0,1,1,0,1]) 


logreg = LogisticRegression(solver='lbfgs', multi_class='auto')

#KFold: 3개 분할 => 3번 교차 
# 랜덤하게 섞기
kf = KFold(shuffle=True, random_state=0) 
print("교차 검증 점수:\n",cross_val_score(logreg, x_data, y_data, cv=kf))


교차 검증 점수:
 [1.  0.5 1. ]


C:\Users\User\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:426: FutureWarning: You should specify a value for 'n_splits' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(NSPLIT_WARNING, FutureWarning)


# LOOCV(Leave-One-Out cross-validation)


In [64]:

import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

x_data = np.array([
[2,1],
[3,2],
[3,4],
[5,5],
[7,5],
[2,5],
[9,2]
])
y_data = np.array([0,0,0,1,1,0,1]) 


logreg = LogisticRegression(solver='lbfgs', multi_class='auto')


loovc = LeaveOneOut() #하나 나머지 분할 => 데이터 수만큼 교차

print("교차 검증 점수:\n",cross_val_score(logreg, x_data, y_data, cv=loovc))




교차 검증 점수:
 [1. 1. 1. 0. 1. 1. 1.]
